### ISSUE TITLE
No certificate found with the supplied thumbprint: F466A3D48EC9E164B60856CC2E3630CB1B2E43AA

### ISSUE THREAD

**Issue by JayCroghan** [rocksdanister/weather#10]
When building I get one sole error:

1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(875,5): error : No certificate found with the supplied thumbprint: F466A3D48EC9E164B60856CC2E3630CB1B2E43AA

If I find an answer later I will post the fix.

**Comment by rocksdanister** [comment]
UWP build package needs to be signed before installation, if you are building it for personal use provide your own certificate in the option which should remove mine or delete these lines:
https://github.com/rocksdanister/weather/blob/3c37da3b0f5718edee2c9f6c0ed84b19de2ea4bc/src/Drizzle.UI.UWP/Drizzle.UI.UWP.csproj#L28-L30
