### ISSUE TITLE
Displays wrong temperature

### ISSUE THREAD

**Issue by sharpninja** [rocksdanister/weather#13]
This morning the app claims the temp is 74F but in reality it is about 58F.  I think it may be using the predicted temperature and is having a timezone issue.

**Comment by rocksdanister** [comment]
Temperature is not affected by timezone.

For daily temperature I am taking the midrange of Maximum and Minimum temp at 2m:
https://open-meteo.com/en/docs

**Comment by AEGAGH** [comment]
Great work! but in my town we don't have snow, I live in Funza Cundinamarca Colombia

**Comment by rocksdanister** [comment]
The weather animation is based on the weather code:
<img width="224" alt="image" src="https://github.com/rocksdanister/weather/assets/17554161/26dabea3-05c0-4015-b0d8-7649208cf521">

What did say for your city?
https://open-meteo.com/en/docs

**Comment by sharpninja** [comment]
> Temperature is not affected by timezone.
> 
> For daily temperature I am taking the midrange of Maximum and Minimum temp at 2m: https://open-meteo.com/en/docs

I'm trying not to be overly critical as the app is beautiful and I love it, but normal expectations of a weather app are to show current temperature, the day's expected high, and the day's expected low.  A midrange isn't really useful.  For example, our temperature range today locally was a low of 58F and high of 90F.  The midrange would only happen for about a minute in early morning.

**Comment by rocksdanister** [comment]
>I'm trying not to be overly critical as the app is beautiful and I love it

Feedback is always welcome and PR even more :)

As to why midrange for some values I am working with whats available with the provider, there is no current temperature field for Open-Meteo from the docs I linked.

However there is hourly temperature values, I will try to select the temperature and other values for the current hour.
