### ISSUE TITLE
Background image suggestion 

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/weather#18]
The application will include many backgrounds and switch between them at random based on weather.
Here you can suggest background images for the weather. The images will be blurred to reduce runtime cost of blurring and better storage compression.

**Format**
Comment in the following format:
```
[Image Link]
Weather: Rain, Snow, Fog, Clear (mouse parallax depth effect.)
```
Do **not** upload any images here directly!😅

**Sources for image**
Image has to have compatible license with attribution being the only requirement, use the following places to find image:
https://www.pexels.com
https://make.wordpress.org/themes/handbook/review/resources/#recommended-websites-for-images

**Additional context**
Users can select any image file in the screensaver/playground mode but this is not true for the rest of the app (for now.)

**Comment by tjsuominen** [comment]
Related to live Windows wallpaper? That would be really neat!

**Comment by tjsuominen** [comment]
Any chance the current app background could be extended as windows live wallpaper? That would be very neat!
