### ISSUE TITLE
Frame rate control

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/weather#2]
Some effects can be run at lower fps (say 24fps) without much noticeable difference thereby reducing resource usage.

**Ref:**
https://github.com/Sergio0694/ComputeSharp/blob/main/src/ComputeSharp.UI/IFrameRequestQueue.cs

**Comment by owosoup** [comment]
I'll second this by mentioning how more powerful GPUs will run effects as fast as possible, ramping up the wattage super high.
It would be great to have a frame rate cap/control because my fans simply redline instantly.
