### ISSUE TITLE
Night Backgrounds and Moon instead of sun when night 

### ISSUE THREAD

**Issue by Gatorzgaming** [rocksdanister/weather#27]
Just like any other weather app, having it be sunny at 3AM is kinda silly, Some moon icons that maybe even reflect the cycle of the moon would be nice

**Comment by rocksdanister** [comment]
Current weather api don't provide moon cycles.

As for the background it requires some work:

- Include day/night backgrounds separately.
- Determine if its day/night for each location using timezone and system time.

The original plan was to simulate day/night using shader code (color shift.) but didn't get time to complete.
