### ISSUE TITLE
Fetch weather periodically

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/weather#3]
Right now weather is only updated on launch, it will be better to periodically (say every 1hr) to update weather while application is open.

**Ref:**
https://learn.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-an-inproc-background-task

**Comment by rocksdanister** [comment]
I dont get you, what do you mean by customizable?

I thought this was required for basic weather app.

**Comment by itsWindows11** [comment]
I meant like, so the user can set it to refresh every 1 min, 5 mins, 10 mins, 30 mins etc.

**Comment by rocksdanister** [comment]
Nah, the disk cache is set to expire in 1hr so best to check hourly.

**Comment by magicalunicor** [comment]
hi! i'm trying to work on it, I just started...
I was looking around and I think that to make this I should just call "UpdateWeather()" inside the shellViewModel using a background task, correct?

**Comment by rocksdanister** [comment]
Refresh maybe better since it clears the cache otherwise if update is called less than hour long (cache duration) it will still use cache:

https://github.com/rocksdanister/weather/blob/7a6783fb3d4fba1b9ffa3ecec4985abd7093cd0f/src/Drizzle.UI.Shared/ViewModels/ShellViewModel.cs#L241-L255

**Comment by magicalunicor** [comment]
Using the reference you provided, I couldn't do it.
I was able to make a timer that fired every X amount of time this way:
`  public class BackgroundTask
  {
      private ThreadPoolTimer timer;

      public BackgroundTask()
      {
          uint timerPeriod = 60 * 1;

          // Create a ThreadPoolTimer that fires the TimerElapsed method every 60 minutes
          timer = ThreadPoolTimer.CreatePeriodicTimer(TimerElapsed, TimeSpan.FromSeconds(timerPeriod));
      }

      private async void TimerElapsed(ThreadPoolTimer timer)
      {
         console.WriteLine("Hello world");
      }
  }

  private void SetupBackgroundInProcessTask()
  {
      BackgroundTask bgTask = new BackgroundTask();
  }`
by calling "SetupBackgroundInProcessTask()" inside the SetWeather() (it should probably be called on the load only).

Still, I am not able to call the refresh. Keep on getting error CS0120. 

Maybe this needed a singleton design pattern. Or maybe I am not skilled enough haha

**Comment by tabularasa138** [comment]
Did this ever get added?  I would also like this feature.  Auto Refresh after one hour would be great.

**Comment by rocksdanister** [comment]
No but if the cache is expired (last checked more than 1hr ago) it should refresh when you re-open the app.

New features are on hold at the moment as I am trying to port this app to MacOS and Linux.

**Comment by tabularasa138** [comment]
Ah, I keep the app open all the time on one of my monitors.

**Comment by jkn108** [comment]
Same.
I have it always opened on a 2nd monitor.
I love that the animation disables when the app isn't in focus so it's not distracting when working in the other monitor but it would be great to have it refresh periodically.
