### ISSUE TITLE
Can you set current state to your wallpaper?

### ISSUE THREAD

**Issue by Nikzed** [rocksdanister/weather#32]
I am an active user of Lively Wallpaper, and I am curious can I make the weather appear as my animation to screen instead of wallpaper? Will this feature be added? I am really curious because the animation is so good.

**Comment by rocksdanister** [comment]
> I am curious can I make the weather appear as my animation to screen instead of wallpaper?

I am guessing you want a live wallpaper version of this? I do get that request a lot.. I am busy at the moment updating Lively app.
