### ISSUE TITLE
allow NOAA as a weather source

### ISSUE THREAD

**Issue by keshka** [rocksdanister/weather#42]
Please allow this website as a source of weather data: https://www.weather.gov/
it allows a user to enter a set of coordinates and predicts weather for an area of about one mile. I have been using this forecast method for years and find it the most accurate source. Most other sources obtain the forecast from NOAA but interpret it.... incorrectly.  Open-metro apparently does the same. The results it indicates for my area (only as close as the zip code) are off by quite a bit from actual. 

Thank you!
Keshka Kotera
Summerville, Oregon

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/weather/issues/14

Best to keep discussion about weather source in one place.
