### ISSUE TITLE
Detect my location

### ISSUE THREAD

**Issue by MrPropre** [rocksdanister/weather#45]
Thank you for making this weather app, it's so much better than the MSN one. The only feature I miss is automatic detection of current location. I often travel between multiple cities in my country, and I have a laptop so it would be easier to just detect my location.

Thank you in advance!

**Comment by rocksdanister** [comment]
There is Windows API to get latitude and longitude but the issue is to get the city name will need reverse geocoding support from the open-meteo provider https://github.com/open-meteo/geocoding-api/issues/6

**Comment by JaneATM** [comment]
Ystem.Net.Http.HtpRequestException：发送请求时出错->System.Exception：无法我到与借误码关联的文本
无法与服务器建立连接
在Svstem.Runtime.Exceptions
Ispatchinfo.Throw0+Ox21
在System.Runtime.CompilerSen
ThrowFornon-Success(任务)+0x70
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)+0x38
在Svstem.Runtime.CompilerSe
在Svstem.Runtime.CompilerServi
Waiter.ValidateEnd(任务)+0x17
15.MoveNext 0)+0x79d
在Svstem.Net.Htto.HttoHandlerToFilter
-堆栈跟踪的末尾
抛出异常的地方--
命令0+0x21
在Svstem.Runtime.Exceptior
在系统运行时间。
ThrowFornon-Success(任务)+0x70
在系统运行时间。
HandlenonSuccessandDebuggerNotification(Task)+0x38
在System.Runtime
(Va IdateEndCask)+Ox17
奥莫
113.MoveNext 0)+0x2c9
获取不到位置信息啊 为啥
