### ISSUE TITLE
location occur exception

### ISSUE THREAD

**Issue by RobertChou** [rocksdanister/weather#50]
![屏幕截图 2024-01-06 012822](https://github.com/rocksdanister/weather/assets/4404703/36e83c36-ebc0-401b-8021-37f34a77f3f1)
![屏幕截图 2024-01-06 012849](https://github.com/rocksdanister/weather/assets/4404703/a3ab673e-8c23-4811-807b-b2c4b1f593c1)

**Comment by rocksdanister** [comment]
New API key take time to activate, try after a day or two.
