### ISSUE TITLE
Unit Measure - Support Uk units

### ISSUE THREAD

**Issue by ryanbowden** [rocksdanister/weather#6]
In the Uk it is common for us to use a hybrid units,
- temperature Celsius 
- Speed MPH

Can you add this for UK, sorry we are strange with different metrics :D

**Comment by rocksdanister** [comment]
That does sound strange xD

On first run I am setting default to imperial in US, for UK the code it should be GB?
https://github.com/rocksdanister/weather/blob/d1992606e763f6259608a7da06e10cd031ae844d/src/Drizzle.UI.UWP/App.xaml.cs#L92-L98

**Comment by ryanbowden** [comment]
![Screenshot_20230928_112218_AccuWeather](https://github.com/rocksdanister/weather/assets/3787875/fac33a93-5707-4a8d-95b9-dc5c8de28252)

Here an example how other weather apps do it by calling it a hybrid. Like you say.
Yeah UK or GB cant remember how it shows. But as long of option exists to switch to hybrid works.

**Comment by rocksdanister** [comment]
New update with hybrid unit started rolling out (v1.0.15.0) 🥳
