### ISSUE TITLE
Norton detects it as WS.Reputation.1 and deleted the installation file.

### ISSUE THREAD

**Issue by sakibstime** [rocksdanister/weather#67]
Hello,
Norton detects it as WS.Reputation.1 and deleted the installation file.

What to do?

Is this a serious issue or ignorable?

![Screenshot 2024-04-07 012848](https://github.com/rocksdanister/weather/assets/35632316/592abfa5-6d31-434b-b998-f89ab4987c77)

**Comment by rocksdanister** [comment]
The installer script is from Microsoft store and its just downloading from Store. 

Get it directly:
https://apps.microsoft.com/store/detail/9PP0MFQFVSC5
