### ISSUE TITLE
Cursor glitches/bounces around when on any graphical setting but potato

### ISSUE THREAD

**Issue by linkinkampf19** [rocksdanister/weather#73]
Just opened Lively Weather today and got some strange bouncy cursor issues. It almost looks like the window keeps trying to resize itself, and the cursor flickers into two or three separate locations in seconds. This only seems to happen if Lively is maximized and has graphics set to anything but potato. If resized to a regular window, the issue disappears. I don't know the best way to get video of this, but I'll update this bug report with something if I'm able to record.

Specs 
Win11 Pro 64bit 22631.3810
Ryzen 7 7700
Gigabyte B650M Aorus Elite AX 
G.Skill 32GB DDR5 6000 MT/s
Radeon RX 7800XT 16GB
500GB m.2 NVMe SSD

**Comment by rocksdanister** [comment]
Were you able to record the issue?

**Comment by linkinkampf19** [comment]
Dani,

So sorry. I saw your response a couple days ago and then time got away from
me. I was not able to record the issue, however I"m noting that now, that
if you've pushed an update already, or perhaps something on the video
driver side was tweaked, things seem to be good again. Thanks again for
checking up!

I wish you the best with this app and Lively Desktop. You've done something
awesome here.

Kyle
