### ISSUE TITLE
FR: Live Animation styles

### ISSUE THREAD

**Issue by tjsuominen** [rocksdanister/weather#80]
Create ability to have different styles for live animation, e.g. cartoon / paperwork (e.g. Android Froggy style, just an example).

**Comment by rocksdanister** [comment]
Lively Weather started out with the idea - What if GPU shaders for the background? and the whole app interface is design around the shader animation.

Implementing a different animation styles is a significant investment in time (full redesign) and cost (I can't draw.. will have to hire etc..) which also does not align with the original goal of the project.. so I am closing this.
