### ISSUE TITLE
Translation of the country, province, state, etc. in displayed language

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/weather#94]
A small bug:
![image](https://github.com/user-attachments/assets/a4cd6256-21b7-4eaf-b06a-45201180c780)
![image](https://github.com/user-attachments/assets/4f626cce-47a3-4b6f-ac56-792257d86448)

I'm not sure if this is already a known issue, I thought I just might add it in case:
The cities is translated correctly but the state and the country always are in English.
e.g. in the Example it should be Bayern - Deutschland but it's Bavaria - Germany.

**Comment by rocksdanister** [comment]
This is up to the weather api source.

Openweathermap provides translation when possible.
