### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by vivadavid** [rocksdanister/weather#96]
Hi,

I haven't thoroughly checked out the Spanish translation, but I've found this issue.

"Temperature" is translated as "Barcelona" (the name of a Spanish city), instead of "Temperatura".

English:

![inglés](https://github.com/user-attachments/assets/9d6f7177-7a08-4050-bf45-7aff4ccc7e0c)

Spanish:

![español](https://github.com/user-attachments/assets/23f4b3fa-2ded-4ed2-96a5-1757ed22dc02)

By the way, it would have been more accurate to translate "Feels like" as "Sensación térmica" instead of just "Sensación", but I understand there's a space limititation and the context should complete what's missing.

Thanks!

**Comment by rocksdanister** [comment]
Looks like its one translators recent submissions, removed it.

There is no space limit, you can contribute translation directly:
https://crowdin.com/project/lively-weather
