### ISSUE TITLE
Add auto location 

### ISSUE THREAD

**Issue by trlef19** [rocksdanister/weather#97]
It would be nice if the location updated automatically based on my current location

**Comment by rocksdanister** [comment]
This is not possible due to the open-meteo weather api limitation.

Some providers have a button to detect location: https://github.com/rocksdanister/weather/issues/45

But not worth implementing automatic detection right now since it wont work with the default open-meteo provider.

**Comment by trlef19** [comment]
okay then

**Comment by rocksdanister** [comment]
Keep it open, I'll get to it when open-meteo adds support.
